language: haxe

dist: xenial

haxe:
  - "4.0.0-preview.5"

install:
  - sudo apt-get install libpng16-dev libjpeg-turbo8-dev libturbojpeg libvorbis-dev libopenal-dev libsdl2-dev libmbedtls-dev libuv1-dev
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libturbojpeg.so.0 /usr/lib/x86_64-linux-gnu/libturbojpeg.so
  - pushd example/pumpkin/ && yes | haxelib install main.cpp.hxml main.hl.hxml && popd
  - wget --content-disposition https://github.com/HaxeFoundation/hashlink/archive/1.8.tar.gz
  - tar -xzvf hashlink-1.8.tar.gz
  - pushd hashlink-1.8 && make && sudo make install && popd

script:
  - haxe hxml/app.neko.hxml
  - cd example/pumpkin/
  - neko ../../out/neko/app.n config.xml definitions.xml
  - haxe main.cpp.hxml
  - haxe main.hl.hxml
  - haxe main.hl_c.hxml
  - ./run.cpp.sh
  - ./run.hl.sh
  - ./run.hl_c.sh
